require:
  - rubocop-ordered_methods

plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true
  Exclude:
    - bin/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 100

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/IncludeExamples:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
