name: 🐛 Bug Report
description: Found something broken? Help us fix it.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Your feedback helps make Pennywise better for everyone.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is and what you expected to happen.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your setup
      placeholder: |
        - OS: [e.g. macOS 15.0, Ubuntu 22.04]
        - Ruby version: [e.g. 3.4.0]
        - Pennywise version: [e.g. 0.1.0]
        - Docker version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output (please use code blocks)
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
