blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/aaronmallen/pennywise/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/aaronmallen/pennywise/security/advisories/new
    about: Report security vulnerabilities privately
