name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea that would make Pennywise even better? We'd love to hear it! Remember, we're building financial freedom one feature at a time.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: A clear description of what problem you're trying to solve or what's missing.
      placeholder: "As a user, I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: A clear description of what you want to happen.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Any alternative solutions or features you've considered?
      placeholder: "I've also considered..."

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - "Nice to have"
        - "Would be helpful"
        - "Important for my workflow"
        - "Critical for adoption"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
